---
- hosts: all
  sudo: yes

  tasks:
    - name: ensure all software is installed
      action: apt name={{item}}
      with_items:
        - nginx
        - git

    - name: delete nginx index
      command: rm -rf /usr/share/nginx/html

    - name: install coolsite
      git: repo=https://github.com/holylex/coolsite.git dest=/usr/share/nginx/html update=yes force=yes
